### ISSUE TITLE
Comments on Deployment request messages

### ISSUE THREAD

**Issue by christophenoel** [crim-ca/testbed14#4]
Hello,

I have the following comments on the examples:

1.  For the Applications which are not Workflows, the profile deployment name should be 
 "http://www.opengis.net/profiles/eoc/dockerizedApplication" and not "http://www.opengis.net/profiles/eoc/workflow"

2. Again, for the Applications, it was requested by Peter that the Execution Unit remains the docker reference and not the CWL. The CWL should be embedded in owsContext, for example:
` "owsContext" : {
        "offering" : {
          "code" : "http://www.opengis.net/eoc/applicationContext/cwl",
          "content" : {
            "href" : "http://some.host/applications/cwl/multisensor_ndvi_stack_generator.cwl"
          }
        }`

3. For compliance with the last version of WPS-T (by NextGen thread), the openAPI interface was modified, and should looks like follow (href instead of reference, and deploymentProfile block disappeared):
` "executionUnit" : [ 
    { 
        "href" : "docker-registry.crim.ca/ogc-public/snap6-stack-creation:v2.1"
    }],
  "deploymentProfileName" : "http://www.opengis.net/profiles/eoc/dockerizedApplication"
}`

**Comment by fmigneault** [comment]
resolved via https://www.crim.ca/stash/projects/OGC/repos/testbed14-twitcher/pull-requests/10

**Comment by dbyrns** [comment]
And for the deploy requests : https://github.com/crim-ca/testbed14/pull/5
